export const routes = {
  index: "/",
  blog: "/blog",
  blogWhyRegisterCourse:
    "/blog/why-should-i-register-for-a-course-when-i-can-self-learn",
  research: "/research",
  researchNigeriaJointResponse:
    "/research/nigeria-joint-response-dutch-ministry-of-foreign-affairs-oct-nov-2020",
  researchUsaidNigeria: "/research/usaid-nigeria-dec-2020-jan-2021",
  researchMercyCorps: "/research/mercy-corps-mar-apr-2021",
  researchJapanInternational:
    "/research/japan-international-cooperation-agency-oct-nov-2021",
  researchSocialImpactUsaid:
    "/research/social-impact-usaid-nigeria-dec-2021-feb-2022",

  whoWeAre: "/who-we-are",
  contactUs: "/contact-us",
  ourTeam: "/our-team",
  ourTeamDrAyo: "/our-team/dr-arowolo-ayoola",
  ourTeamAbdul: "/our-team/abdulsalam-oluwatosin",
  ourTeamSefunmi: "/our-team/sefunmi-oluwole",
  ourTeamLoveth: "/our-team/oche-loveth",
  ourTeamFelicia: "/our-team/felicia-ayodele",
  ourTeamMaranatha: "/our-team/maranatha-emmaogboji",
  ourTeamBlessing: "/our-team/blessing-adem",
  ourTeamMatthew: "/our-team/gabriel-matthew",
  ourTeamIsaac: "/our-team/isaac-joshua",
  ourTeamEniola: "/our-team/oyekale-eniola-yetunde",
  ourTeamAdaora: "/our-team/okona-adaora-stephanie",
  ourTeamStephen: "/our-team/mogaji-adekale-stephen",
  ourTeamMusa: "/our-team/musa-maimusa",
  careers: "/careers",
  courses: "/courses",
  coursesDataAnalytics: "/courses/data-analytics",
  coursesDataAnalyticsNyscPlan: "/courses/data-analytics/nysc-plan",
  coursesDataAnalyticsStandardPlan: "/courses/data-analytics/standard-plan",
  coursesDataAnalyticsPaymentSuccess: "/courses/data-analytics/payment-success",
  coursesDataScience: "/courses/data-science",
  coursesBioInformatics: "/courses/bioinformatics",
  coursesHrAnalytcis: "/courses/hr-analysis",
  coursesBusinessAnalytics: "/courses/business-analytics",
  coursesResearch: "/courses/research-methodology-manuscript-writing",
  coursesEmployability: "/courses/employability-entrepreneurship",
  coursesDigitalCreation: "/courses/digital-creation",
  deafInTech: "/deaf-in-tech",
  consultancy: "/consultancy",
  training: "/training",
  privacyPolicy: "/privacy-policy",
};
